"""Regression tests for the checked-in WeaveMark study corpus."""

import importlib.util
import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
STUDIES_DIR = REPO_ROOT / "studies"
CONTROLLED_STUDIES_DIR = STUDIES_DIR / "controlled-studies"
EXAMPLES_STUDIES_DIR = STUDIES_DIR / "examples-studies"
TOOLS_DIR = STUDIES_DIR / "tools"
CONTROLLED_MD_REPORTS = [
    CONTROLLED_STUDIES_DIR / "results.md",
    *CONTROLLED_STUDIES_DIR.glob("**/results/*.md"),
]
CONTROLLED_HTML_REPORTS = [
    CONTROLLED_STUDIES_DIR / "results.html",
    *CONTROLLED_STUDIES_DIR.glob("**/results/*.html"),
]
EXAMPLE_MD_REPORTS = [
    EXAMPLES_STUDIES_DIR / "results.md",
    *EXAMPLES_STUDIES_DIR.glob("*/results.md"),
]
EXAMPLE_HTML_REPORTS = [
    EXAMPLES_STUDIES_DIR / "results.html",
    *EXAMPLES_STUDIES_DIR.glob("*/results.html"),
]
FORBIDDEN_REPORT_WORDING = (
    "Generated by",
    "generated by",
    "recomputed",
    "Recomputed",
    "regenerated",
    "Regenerated",
    "fresh snippets",
    "Fresh snippets",
)


def _load_report_generator():
    """Load the study report generator without requiring studies to be a package."""
    sys.path.insert(0, str(TOOLS_DIR))
    previous_dont_write_bytecode = sys.dont_write_bytecode
    sys.dont_write_bytecode = True
    try:
        spec = importlib.util.spec_from_file_location(
            "study_report_generator", TOOLS_DIR / "regenerate_reports.py"
        )
        assert spec is not None
        assert spec.loader is not None
        module = importlib.util.module_from_spec(spec)
        sys.modules[spec.name] = module
        spec.loader.exec_module(module)
        return module
    finally:
        sys.dont_write_bytecode = previous_dont_write_bytecode


def _load_blind_analysis_tool():
    """Load the blind-analysis tool without requiring studies to be a package."""
    sys.path.insert(0, str(TOOLS_DIR))
    previous_dont_write_bytecode = sys.dont_write_bytecode
    sys.dont_write_bytecode = True
    try:
        spec = importlib.util.spec_from_file_location(
            "blind_analysis_tool", TOOLS_DIR / "blind_analysis.py"
        )
        assert spec is not None
        assert spec.loader is not None
        module = importlib.util.module_from_spec(spec)
        sys.modules[spec.name] = module
        spec.loader.exec_module(module)
        return module
    finally:
        sys.dont_write_bytecode = previous_dont_write_bytecode


def _load_example_report_generator():
    """Load the example-study report generator without requiring a package."""
    sys.path.insert(0, str(TOOLS_DIR))
    previous_dont_write_bytecode = sys.dont_write_bytecode
    sys.dont_write_bytecode = True
    try:
        spec = importlib.util.spec_from_file_location(
            "example_report_generator", TOOLS_DIR / "regenerate_example_studies.py"
        )
        assert spec is not None
        assert spec.loader is not None
        module = importlib.util.module_from_spec(spec)
        sys.modules[spec.name] = module
        spec.loader.exec_module(module)
        return module
    finally:
        sys.dont_write_bytecode = previous_dont_write_bytecode


def test_study_metric_snapshot_covers_registered_variants():
    generator = _load_report_generator()
    rows = json.loads(
        (CONTROLLED_STUDIES_DIR / "metrics/semantic-information.json").read_text()
    )
    expected_keys = {(variant.study, variant.name) for variant in generator.VARIANTS}
    actual_keys = {(row["study"], row["variant"]) for row in rows}

    assert len(rows) == 27
    assert actual_keys == expected_keys


def test_contrastive_score_registry_covers_every_study():
    generator = _load_report_generator()
    study_ids = {study.study_id for study in generator.STUDIES}

    assert set(generator.SCORES) == study_ids
    for study in generator.STUDIES:
        scores = generator.study_scores(study)
        assert len(scores) == len(generator.CRITERIA)
        assert [score.criterion for score in scores] == list(generator.CRITERIA)
        assert all(-3 <= score.score <= 3 for score in scores)
        assert all(score.rationale for score in scores)


def test_controlled_study_sources_do_not_refine_removed_fragments():
    removed_refinements = (
        "programming/assets/generative-2d-sprites",
        "programming/types/type-2d-game",
    )

    for source_path in CONTROLLED_STUDIES_DIR.glob("**/specs/*.weavemark.md"):
        source = source_path.read_text(encoding="utf-8")
        for refinement in removed_refinements:
            assert refinement not in source, (
                f"{source_path.relative_to(REPO_ROOT)} still refines removed "
                f"fragment {refinement}"
            )


def test_blind_summary_uses_current_run_marker():
    generator = _load_report_generator()

    summary = generator.load_blind_summary()

    assert summary is not None
    assert summary["run_id"] == "20260710T1416-iterate-final"
    assert summary["aggregate_score"] == 89


def test_generated_reports_preserve_standalone_contract():
    assert len(CONTROLLED_MD_REPORTS) == 19

    for report_path in CONTROLLED_MD_REPORTS:
        text = report_path.read_text()
        assert "[View as HTML]" in text
        assert "## Metric definitions" in text or "## Score definitions" in text
        assert "## Contrastive gain/loss scores" in text
        assert "-3 = dramatically worse" in text
        assert "+3 = dramatically better" in text
        assert "[C1]" in text
        assert "[C2]" in text
        assert "[T]" in text
        assert "| **Total** | **" in text or "| Total |" in text
        if report_path == CONTROLLED_STUDIES_DIR / "results.md":
            assert "## Key insights" in text
            assert "## Primary blind* score source" in text
            assert "Aggregate blind contrastive delta*: **+89**" in text
            assert "**Blind delta:**" in text
            assert "../outputs/studies/blind-analysis/" in text
            assert "20260710T1416-iterate-final" in text
            assert "20260710T1521-transit-iterate" not in text
            assert "Orbital Drift (+11)" in text
            assert "Negative deltas:** none in the active score source" in text
            assert "single-output studies in this corpus" in text
            assert "9 wins" not in text
            assert "Criterion-specific blindness" in text
            assert "Input readability | masked-source review" in text
        else:
            assert "Blind* score" in text
        for forbidden in FORBIDDEN_REPORT_WORDING:
            assert forbidden not in text


def test_html_reports_are_synchronized_and_glanceable():
    assert len(CONTROLLED_HTML_REPORTS) == 19
    md_stems = {
        path.relative_to(CONTROLLED_STUDIES_DIR).with_suffix("")
        for path in CONTROLLED_MD_REPORTS
    }
    html_stems = {
        path.relative_to(CONTROLLED_STUDIES_DIR).with_suffix("")
        for path in CONTROLLED_HTML_REPORTS
    }
    assert html_stems == md_stems

    for report_path in CONTROLLED_HTML_REPORTS:
        text = report_path.read_text()
        assert "<!doctype html>" in text
        assert "Markdown report" in text
        assert "score-chip" in text
        assert "Metric definitions" in text or "Score definitions" in text
        assert "details-panel" in text
        assert "definition-grid" in text
        assert "score-positive" in text
        assert "score-positive-3" in text or "score-positive-2" in text
        assert "score-negative" in text or "score-neutral" in text
        if report_path == CONTROLLED_STUDIES_DIR / "results.html":
            assert "report-header" in text
            assert "score-matrix" in text
            assert "score-heat" in text
            assert "score-mark" in text
            assert "Key insights" in text
            assert "9/9 positive" in text
            assert "single-output studies in this corpus" in text
            assert "Study and comparison" in text
            assert "Authoring<br>leverage" in text
            assert "Constraint<br>integration" in text
            assert "metric-number winner" in text
            assert "metric-number loser" in text or "metric-number tie" in text
            assert "metric-tile metric-win" in text
            assert "metric-tile metric-loss" in text
            assert "Primary blind* score source" in text
            assert "Primary blind* delta" in text
            assert "Blind absolute score" in text
            assert "Criterion-specific blindness policy" in text
            assert "blind-score-table" in text
            assert "Open derandomized blind report" in text
            assert "derandomized-report.html" in text
        if report_path.name == "ablation-summary.html":
            assert "value-chip winner" in text
            assert "value-chip loser" in text or "value-chip tie" in text
        assert "[C1]" in text
        assert "[C2]" in text
        assert "[T]" in text
        assert "-3..+3" in text
        assert "Total" in text
        for forbidden in FORBIDDEN_REPORT_WORDING:
            assert forbidden not in text

    consolidated = (CONTROLLED_STUDIES_DIR / "results.html").read_text()
    assert "Exploratory outcome" in consolidated
    assert "legend-row" in consolidated
    assert "Post-reveal metric race" in consolidated
    assert "race-card" in consolidated
    assert "Key caveats to notice" in consolidated
    assert 'class="hero"' not in consolidated
    assert "<th>Control</th>" not in consolidated
    assert "<th>Treatment</th>" not in consolidated
    assert "<th>Main failure</th>" not in consolidated


def test_final_quality_reports_include_verbatim_snippets():
    quality_reports = sorted(
        CONTROLLED_STUDIES_DIR.glob("**/results/final-quality-analysis.md")
    )
    assert len(quality_reports) == 9

    for report_path in quality_reports:
        text = report_path.read_text()
        assert "## Verbatim snippets" in text
        assert "source seam" in text
        assert text.count("### [C1]") == 1
        assert text.count("### [C2]") == 1
        assert text.count("### [T]") >= 1


def test_final_quality_html_reports_include_verbatim_snippets():
    quality_reports = sorted(
        CONTROLLED_STUDIES_DIR.glob("**/results/final-quality-analysis.html")
    )
    assert len(quality_reports) == 9

    for report_path in quality_reports:
        text = report_path.read_text()
        assert "Verbatim snippets" in text
        assert "snippet-card" in text
        assert "source/output material" in text


def test_repo_skill_captures_study_reporting_contract():
    skill = (
        REPO_ROOT / ".github/skills/weavemark-study-reporting/SKILL.md"
    ).read_text()

    assert "name: weavemark-study-reporting" in skill
    assert "Markdown and HTML reports are synchronized companions" in skill
    assert "studies/controlled-studies/" in skill
    assert "studies/examples-studies/" in skill
    assert "[C1]" in skill and "[C2]" in skill and "[T]" in skill
    assert "-3..+3" in skill
    assert "intention fit" in skill
    assert "green gain, red loss, amber/yellow neutral" in skill
    assert "do not need to mirror the Markdown structure exactly" in skill
    assert "metric race cards" in skill
    assert "metric glossary" in skill
    assert "criterion-aware blind* scores" in skill
    assert "score-hybrid" in skill
    assert "heatmap-style" in skill
    assert "blind_analysis.py metric-pass" in skill
    assert "derived-evidence" in skill
    assert "copilot --version" in skill


def test_example_study_reports_are_absolute_quality_checks():
    generator = _load_example_report_generator()
    rows = json.loads(
        (EXAMPLES_STUDIES_DIR / "metrics/example-quality.json").read_text()
    )

    assert len(generator.EXAMPLES) == 9
    assert len(rows) == len(generator.EXAMPLES)
    assert len(EXAMPLE_MD_REPORTS) == 10
    assert len(EXAMPLE_HTML_REPORTS) == 10
    assert {row["example_id"] for row in rows} == {
        example.example_id for example in generator.EXAMPLES
    }

    consolidated_md = (EXAMPLES_STUDIES_DIR / "results.md").read_text()
    consolidated_html = (EXAMPLES_STUDIES_DIR / "results.html").read_text()
    assert "WeaveMark Example Studies" in consolidated_md
    assert "without contrastive controls" in consolidated_md
    assert "Average rubric score" in consolidated_md
    assert "No leakage/pathologies" in consolidated_md
    assert "[C1]" not in consolidated_md
    assert "[T]" not in consolidated_md
    assert "Primary blind* score source" not in consolidated_html
    assert 'Controls</p><p class="kpi-value">None' in consolidated_html
    assert "Rubric detail" in consolidated_html
    assert "details-panel" in consolidated_html
    for report_path in (*EXAMPLE_MD_REPORTS, *EXAMPLE_HTML_REPORTS):
        assert report_path.exists()
        text = report_path.read_text()
        assert "View as HTML" in text or "Markdown report" in text
        for forbidden in FORBIDDEN_REPORT_WORDING:
            assert forbidden not in text


def test_blind_analysis_prepares_derived_evidence_packets(tmp_path):
    blind = _load_blind_analysis_tool()

    run_dir = blind.prepare_blind_run(
        output_root=tmp_path,
        run_id="blind-test",
        seed=1234,
        mode="derived-evidence",
    )

    manifest = json.loads((run_dir / "manifest.json").read_text())
    template = json.loads((run_dir / "blinded_scores.template.json").read_text())
    key = json.loads((run_dir / "private/key.json").read_text())
    packet_paths = sorted((run_dir / "packets").glob("*/*.md"))
    evidence_paths = sorted((run_dir / "derived-evidence").glob("*/*.json"))

    assert manifest["mode"] == "derived-evidence"
    assert "derived-evidence mode avoids raw text review" in manifest["blindness_note"]
    assert len(packet_paths) == 27
    assert len(evidence_paths) == 27
    assert "promplet" not in (run_dir / "manifest.json").read_text().lower()
    assert "[T]" not in (run_dir / "blinded_scores.template.json").read_text()
    assert key["studies"]

    first_packet = packet_paths[0].read_text()
    first_evidence = json.loads(evidence_paths[0].read_text())
    assert "Mode: derived-evidence" in first_packet
    assert "## Derived metric summary" in first_packet
    assert "## Source material" not in first_packet
    assert "## Compiled output" not in first_packet
    assert "[C1]" not in first_packet
    assert "[C2]" not in first_packet
    assert "[T]" not in first_packet
    assert "WeaveMark" not in first_packet
    assert first_evidence["metrics"]["output_words"] > 0
    assert first_evidence["fact_candidate_count"] == len(
        first_evidence["fact_candidates"]
    )
    assert template["studies"][0]["variants"][0]["scores"]


def test_blind_analysis_reveals_after_anonymous_scoring(tmp_path):
    blind = _load_blind_analysis_tool()

    run_dir = blind.prepare_blind_run(
        output_root=tmp_path,
        run_id="blind-test",
        seed=4321,
    )
    scores_path = blind.write_metric_scores(run_dir)
    report_path = blind.reveal_scores(run_dir, scores_path)
    html_report_path = report_path.with_suffix(".html")
    json_report_path = report_path.with_suffix(".json")

    anonymous_scores = scores_path.read_text()
    report = report_path.read_text()
    html_report = html_report_path.read_text()
    json_report = json.loads(json_report_path.read_text())
    assert "[T]" not in anonymous_scores
    assert "[C2]" not in anonymous_scores
    assert "WeaveMark treatment" not in anonymous_scores
    assert "# Blind Study Analysis" in report
    assert "[T] WeaveMark treatment" in report
    assert "Blind contrastive delta" in report
    assert "## Metric definitions" in report
    assert "Total blind contrastive delta across studies" in report
    assert json_report["aggregate_delta"] == 62
    assert json_report["studies"][0]["study_id"]
    assert json_report["studies"][0]["deltas"]
    assert "<!doctype html>" in html_report
    assert "Metric definitions" in html_report
    assert "details-panel" in html_report
    assert "Blind Study Analysis" in html_report


def test_blind_analysis_composes_hybrid_scores(tmp_path):
    blind = _load_blind_analysis_tool()

    run_dir = blind.prepare_blind_run(
        output_root=tmp_path,
        run_id="hybrid-test",
        seed=2468,
        mode="source-and-output",
    )
    template = json.loads((run_dir / "blinded_scores.template.json").read_text())
    qualitative_payload = {
        "schema_version": blind.SCHEMA_VERSION,
        "run_id": "hybrid-test",
        "mode": "source-and-output",
        "score_scale": "Absolute 1..7 per criterion; higher is better.",
        "score_source": "test-masked-review",
        "criteria": list(blind.MASKED_REVIEW_CRITERIA),
        "studies": [
            {
                "study_id": study["study_id"],
                "title": study["title"],
                "variants": [
                    {
                        "anonymous_id": variant["anonymous_id"],
                        "scores": {
                            criterion: 4 for criterion in blind.MASKED_REVIEW_CRITERIA
                        },
                        "notes": "Neutral masked-review fixture score.",
                    }
                    for variant in study["variants"]
                ],
            }
            for study in template["studies"]
        ],
    }
    qualitative_path = run_dir / "blinded_scores.qualitative.json"
    qualitative_path.write_text(json.dumps(qualitative_payload), encoding="utf-8")

    hybrid_path = blind.write_hybrid_scores(run_dir, qualitative_path)
    report_path = blind.reveal_scores(run_dir, hybrid_path)
    json_report = json.loads(report_path.with_suffix(".json").read_text())

    assert hybrid_path.name == "blinded_scores.hybrid.json"
    assert json_report["score_source"] == "hybrid-derived-metrics-and-masked-review"
    assert json_report["criterion_methods"]["Input readability"]["blindness"] == (
        "masked-source review"
    )
    assert "weak length/density proxies" in json_report["leak_risk_note"]
